
services:
    php:
        container_name: eye_clinic
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel_net
        depends_on:
            - mysql

    nginx:
        image: nginx:latest
        ports:
            - "8081:80"
        volumes:
            - .:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_net
        depends_on:
            - php

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: skincare
            MYSQL_USER: laravel
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_net

    redis:
        image: redis:alpine
        networks:
            - laravel_net

volumes:
    mysql_data:

networks:
    laravel_net:
        driver: bridge
